version: 2

jobs:
  build:
    docker:
      - image: 'noroozpour/gearoenix:0.0.1'
    steps:
      - checkout
      - run:
          name: Updating OS
          command: 'apt update && apt dist-upgrade -y'
      - run:
          name: Setup dependancies
          command: 'python3 ./setup.py'
      - run:
          name: Cmake run
          command: 'cmake .'
      - run:
          name: Make run
          command: 'make'
      - run:
          name: CTest run
          command: 'ctest'