version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: 'noroozpour/gearoenix:0.0.1'
    steps:
      - checkout
      - run:
          name: Updating OS
          command: 'apt update && apt dist-upgrade -y'
      - run:
          name: Setup dependancies
          command: 'python3 ./setup.py'
      - run:
          name: Cmake run
          command: 'mkdir build; cd build; rm -rf *; cmake -B. -H.. -DCMAKE_BUILD_TYPE=Debug -DGX_ENABLE_TESTS=ON -DGX_ENABLE_COVERAGE=ON .'
      - run:
          name: Build and tests run
          command: 'cmake --build . --config Debug --target GX_COVERAGE -- -j4'
      - codecov/upload:
          flags: unittest
          file: 'GX_COVERAGE.info'
          conf: '.circleci/codecov.yml'
