version: 2
jobs:
  build:
    docker:
      - image: ubuntu:19.04
    steps:
      - checkout
      - run:
        name: Updating OS
        command: 'apt-get update; apt-get dist-upgrade -y'
      -run:
        name: Installing Python 3
        command: 'apt-get install -y python3'