version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Updating OS
          command: 'apt-get update && apt-get dist-upgrade -y'
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing Compilers
          command: 'apt-get update && apt-get install -y gcc g++ make'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Python3
          command: 'apt-get update && sudo apt-get install -y python3'
      - run:
          name: Setup dependancies
          command: 'python3 ./setup.py'
      - run:
          name: Cmake run
          command: 'cmake .'
      - run:
          name: Make run
          command: 'make'
      - run:
          name: CTest run
          command: 'ctest'